# Generated by Django 2.0.6 on 2018-06-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='relation_type',
        ),
    ]
